### PR TITLE
Fixed Unhandled Rejection error for awarenesscontent and ramanihuria

### LINKED ISSUE #4: Unhandled Rejection (Error): Cannot find module './dummyproject/AwarenessContent'.
image
also in ramani huria
image

### PR DESCRIPTION
**Pull request by VarunBhandia**
Fixed #4 and #3

### CODE REVIEW

**Comment by VarunBhandia** [comment]
Please review my changes @ramyaragupathy, @xamanu  and @smit1678

**Comment by ramyaragupathy** [comment]
Looking at this @VarunBhandia

**Comment by ramyaragupathy** [comment]
@VarunBhandia - I am still seeing a bunch of files irrelevant to the issue.  Do you still want me to look at this PR or this is the new one https://github.com/hotosm/hot-dashboard/pull/8?

**Comment by VarunBhandia** [comment]
@ramyaragupathy yes ma'am please look to the new PR #8 ignore this one .

**Comment by ramyaragupathy** [comment]
Per chat w/  @VarunBhandia - this PR is not relevant anymore

**Pull request closed without merging**
